version: '3.3'

services:
  mongo:
    image: mongo:4.4.16
    container_name: mongo-condor
    command: mongod --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
